### ISSUE TITLE
Question about data

### ISSUE THREAD

**Issue by nemo0526** [dyhBUPT/OMG#1]
Hello, may I ask that where should I put both the data from baidu and the data from aicity in?

**Comment by dyhBUPT** [comment]
Hi, what do you mean of "from baidu"?

**Comment by nemo0526** [comment]
The data you mentioned in data preparation.

**Comment by dyhBUPT** [comment]
They are inputed together with the raw data. You can see them in our provided data (https://pan.baidu.com/s/1rxmlk-XZVTi5tjKOHTRAXg) named as "xxx_nlpaug"
