### ISSUE TITLE
Baidu Link is not working

### ISSUE THREAD

**Issue by kajal15003** [dyhBUPT/OMG#2]
Dear Team
It's really nice work. I want to reproduce the results but Baidu link for data preparation is not working.
Could you please provide it again?

**Comment by dyhBUPT** [comment]
Hi, it seems the link is fine.
Maybe you can try it again?

**Comment by kajal15003** [comment]
Thanks for quick response! I tried on two different devices with different networks but not able to open. Is there any other way to share? 
And also, it is saying there is no transformer when I run train.py. Is it also part of data preparation?

**Comment by dyhBUPT** [comment]
It seems abnormal. I also tried on two different devices, and it works.
I don't have these data stored anywhere else...

For missing `transformer`, please refer to "requirements.txt".

Best wishes.

**Comment by kajal15003** [comment]
Hi,
The problem is due to Baidu. I guess it is unstable outside China. Is it possible for you to upload a copy to one drive?

**Comment by dyhBUPT** [comment]
Hi, I'm sorry but I don't have enough room on onedrive. Maybe VPN will help you.
