### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by mangenasuswetha** [dyhBUPT/OMG#4]
Hello, Could you please Where i can download the checkpoints !

Thank you!

**Comment by dyhBUPT** [comment]
Hi, I'm sorry but we didn't provide the ckpt files.
Please try to train the model from scratch.

**Comment by mangenasuswetha** [comment]
Hello! Thank you for the reply!
But can you please either tell where i can download or upload it !

**Comment by dyhBUPT** [comment]
There is no place to download it.
